params:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: mnist_shard_descriptor.MnistShardDescriptor
  #template: mnist_shard_descriptor_with_data_splitter.MnistShardDescriptor
  params:
    data_folder: mnist_data
    rank_worldsize: 1,10
